batch_size: 32
epochs: 30
lr: 0.001
weight_decay: 0.0001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False


data_dir: data

# Evaluation
model_path: outputs/2024-07-18/11-09-10/model_best.pt